### ISSUE TITLE
crashes from time to time

### ISSUE THREAD

**Issue by omni6** [gort818/qtwebflix#1]
hey Alessandro,

do you noticed this crashes of the widevine part, sometimes. But when there is a reload or shifting the postition needed. just curious if is just in my setup. i believe it is upstream....

**Comment by gort818** [comment]
I haven't had any crashes, can you show me the output?

**Comment by omni6** [comment]
ehh at the moment qt5-webengine-widevine doesnt work at all. i had to switch in to kde-unstable branch for testing purposes. this webengine version misses the properitary codecs, so no qtwebflix atm. but i think i cant trace that anyhow, nothing qt related crashes... 
netflix screen: an error occurred please....  error code ...  so far i remember. 

i will report when qt 5.10 comes in stable repo.

**Comment by omni6** [comment]
not much, but here we go:

```
../../../../qtwebengine-opensource-src-5.9.2/src/3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0025
Received signal 11 SEGV_MAPERR 000000000019
#0 0x7efc881b04e2 <unknown>
#1 0x7efc8670f920 <unknown>
#2 0x7efc88d5853c <unknown>
#3 0x7efc88d60549 <unknown>
#4 0x7efc8670f920 <unknown>
#5 0x7efc867d1bea __GI___mremap
#6 0x7efc86758ad0 mremap_chunk
#7 0x7efc8675e181 __GI___libc_realloc
#8 0x7efc6fdd9491 <unknown>
#9 0x7efc6fdda878 <unknown>
#10 0x7efc6fdd8910 <unknown>
#11 0x7efc6fdd8400 <unknown>
#12 0x7efc6fdd818d <unknown>
#13 0x7efc6fdc917e <unknown>
#14 0x7efc6fdc8df4 <unknown>
#15 0x7efc8d773aa4 <unknown>
#16 0x7efc8d7777ec <unknown>
#17 0x7efc88dd9fca <unknown>
#18 0x7efc88ddb7ee <unknown>
#19 0x7efc88d83fbb <unknown>
#20 0x7efc88941923 <unknown>
#21 0x7efc88227003 <unknown>
#22 0x7efc881cb040 <unknown>
#23 0x7efc881cc698 <unknown>
#24 0x7efc881cca2b <unknown>
#25 0x7efc881cdad1 <unknown>
#26 0x7efc881ca3e8 <unknown>
#27 0x7efc881e6e2b <unknown>
#28 0x7efc8818b2cd <unknown>
#29 0x7efc8818f34a <unknown>
#30 0x7efc8818f647 <unknown>
#31 0x7efc88188a09 <unknown>
#32 0x7efc87888daa QtWebEngine::processMain()
#33 0x55ab678eb9a5 <unknown>
#34 0x7efc866fbf6a __libc_start_main
#35 0x55ab678eb9fa <unknown>
  r8: 00001bddba1f7000  r9: 00001bddba1f7000 r10: 00001bddba1f7000 r11: 0000000000000246
 r12: 00007ffcde97f9c4 r13: 00007ffcde97fac0 r14: 00007ffcde97fa00 r15: 000055ab6928dbd0
  di: 0000000000000001  si: 00007efc8bef9e76  bp: 00007ffcde97fa00  bx: 0000000000000019
  dx: 0000000000000000  ax: 0000000000000019  cx: 00007efc867cbc49  sp: 00007ffcde97f9c0
  ip: 00007efc88d5853c efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000019
[end of stack trace]

```

![screenshot_20171020_195846](https://user-images.githubusercontent.com/24492439/31835416-bc97fe3c-b5d1-11e7-9990-7b015776dc01.png)

**Comment by gort818** [comment]
Ok we might just need an update  qt5-webengine-widevine , I will do some tests and find a solution.

**Comment by gort818** [comment]
Ok I just tested I have zero issues everything is still working, do you have chromium installed?

**Comment by gort818** [comment]
@omni6 Ok I just installed  the latest chromium and qtwebflix does not work, so it seems we have a conflict. I uninstalled it and everything works again.

**Comment by omni6** [comment]
no thats the issue i meant. 
this is even worse, on what distro are you? On arch we noticed this already, theoretically it could be that qt5-webengine prefers the libwidevinecdmadapter.so from /usr/lib/chromium installed with the chromium package. [Link](https://aur.archlinux.org/packages/qt5-webengine-widevine/). I dont know how you use/installed the widevine libs. But if one have chromium installed, no addition widevine  stuff should be needed because webengine detects the chromium libs.... but this is not confirmed yet.

**Comment by gort818** [comment]
I tested on Arch and Ubuntu, No crashes on either. Well why not move  libwidevinecdmadapter.so to /usr/lib/chromium? This is what QT says 

> On Linux the Widevine plugin comes with the Google Chrome installation and can be found in “/opt/google/chrome/”, and on some distros such as Arch it also comes as a system package for Chromium and will be under “/usr/lib/chromium/”. The CDM Pepper plugin is named libwidevinecdmadapter.so and depends on libwidevinecdm.so which you can find with it. 

>

**Comment by omni6** [comment]
> Qt Blog wrote:
Qt WebEngine will try to find an already downloaded or installed version of the plugin, but while convinient this might not be enough if you want to ship an application that relies on it being present. In that case you need to extract from Google Chrome and place it in the application or  ‘plugins/ppapi’ folder.

that is what we've done, and it worked long time. the problem why not simply use /usr/lib/chromium are conflicts between chromium packages and webengine packages. same files different owners --> conflict.

**Comment by omni6** [comment]
take a look:
https://bugreports.qt.io/browse/QTBUG-64071

**Comment by gort818** [comment]
@omni6 Ok I will try something later on, let you know how it goes.

**Comment by gort818** [comment]
@omni6 I reinstalled chromium and renamed /usr/lib/chromium/libwidevinecdmadapter.so and
libwidevinecdm.so. Netflix will not work in chromium but qtwebflix will work.

That is all I got so far I cannot do anything on my end.

**Comment by gort818** [comment]
@omni6 I got it!
change the desktop file to
Exec=/usr/bin/netflix --register-pepper-plugins="/usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so; application/x-ppapi-widevine-cdm"

**Comment by gort818** [comment]
or we can just set an alias for netflix , also check the aur package you need to make some changes.

Thanks!

**Comment by omni6** [comment]
all done, works like a charm! Good job :)

**Comment by gort818** [comment]
Awesome thanks for your patience!

**Comment by omni6** [comment]
you should consider to announce qtwebflix on e.g https://www.reddit.com/r/kde/ or https://www.reddit.com/r/linux/. i think it has the ability to get much more used, problem is that nobody knows it. There is a lack for packaging in various distros, you really should make it more popular.

**Comment by omni6** [comment]
You should consider to announce qtwebflix e.g at https://www.reddit.com/r/linux/ or https://www.reddit.com/r/kde/. At the moment there's a lack for packaging in various distros. If you make it more popular i think it will be used much, much more. Good software!

**Comment by omni6** [comment]
the thread is a mess OMFG!!!!!

**Comment by omni6** [comment]
but you get attention :+1:
