### ISSUE TITLE
Blink deferred a task warning

### ISSUE THREAD

**Issue by ryanmusante** [gort818/qtwebflix#10]
I receive this warning from journalctl regularly. Is it something to ignore?

`netflix[915]: js: Blink deferred a task in order to make scrolling smoother. Your timer and network tasks should take less than 50ms to run to avoid this. Please see https://developers.google.com/web/tools/chrome-devtools/profile/evaluate-performance/rail and https://crbug.com/574343#c40 for more information.
`

**Comment by gort818** [comment]
@ryanmusante Yeah you can ignore that, Blink is the rendering engine that chromium uses which QtWebEngine is based on, seems as there is a task on Netflix that slows the scrolling so the rendering engine puts a hold on the task to make it smoother.
