### ISSUE TITLE
change name of executable 

### ISSUE THREAD

**Issue by omni6** [gort818/qtwebflix#13]
Because qtwebflix now plays amazon & co maybe change name of executable fom netflix to qtwebflix?

And it would be great if one could disable unuseable streaming providers. Here in germany just amazon and netflix are interesting. Maybe possibility to add and remove providers in a config file. 

Thank you for your work

**Comment by gort818** [comment]
Yeah we can do that, you will have to change the .desktop file.

Yeah the way I did it for the other providers was a quick fix, I will work on a more elegant solution when I have time.

**Comment by omni6** [comment]
in know the .desktop file has to be changed immediately after commit. please announce it.

**Comment by gort818** [comment]
@omni6 I have an incoming fix for this issue and #15

**Comment by gort818** [comment]
Done
