### ISSUE TITLE
Allow users to add and delete streaming services to show in the context menu.

### ISSUE THREAD

**Issue by gort818** [gort818/qtwebflix#15]

**Comment by gort818** [comment]
fixed with  4dfa155

**Comment by omni6** [comment]
this is nice!

**Comment by omni6** [comment]
I played around with the providers.conf, thought it would be usefull to add some standard providers and comment them out. If you provide such a template it would be easier to enable needed services. 
"#" was not recognized for comment out something, the i tried it with ";" this worked as long i closed qtwebflix. The providers.conf restored to default again. 

some of them are interesting, much from usa but also: african, arabic, japanese, australian etc...

All Japan Pro Wrestling TV Acorn TV **Amazon Video** **AnimeLab** CBS All Access **CraveTV** **Crunchyroll** CuriosityStream Club WWN DirecTV Now DDT Universe Demand Progress **ESPN+** FandangoNOW Fandor FilmStruck Foxtel Play Fullscreen FITE TV Global Wrestling Network Google Play Movies & TV HBO Go **HBO** Now Hillsong Channel Now **HOOQ** **Hulu** Honor Club **Icflix** **iflix** iTunes Store **Mubi** **Netflix** New Japan Pro-Wrestling World Nintendo eShop Now TV PlayStation Store PlayStation Video PlayStation Vue Playster Rooster Teeth FIRST SHAHID Showmax Showtime **Shudder** Sky On Demand Sling TV Stan **STARZ** Stardom World TVPlayer UFC Fight Pass VidAngel **Vudu** Warner Archive Instant Windows Store (Microsoft Movies & TV) WWE Network WWNLive YouTube Red

**Comment by gort818** [comment]
A little hacky  but I got # to work as comment now.. this is just a temp solution.. unfortunately QSettings is not really meant to be edited by the user.

**Comment by gort818** [comment]
added a sample providers file to the repo, if you want to add more be my guest :)

**Comment by omni6** [comment]
i'm on it
