### ISSUE TITLE
Set initial window size?

### ISSUE THREAD

**Issue by navdeepio** [gort818/qtwebflix#2]
Is it possible? The default window is too small, have to resize it on each launch..

**Comment by gort818** [comment]
Sure I will set the window to open maximized.

**Comment by gort818** [comment]
fixed with https://github.com/gort818/qtwebflix/commit/68404515cf6200f78fb4d36ddc298c3302d4e921

**Comment by omni6** [comment]
couldn't you make it so that the window manager can remember postition and size? A bit bigger at first startup and all will be fine.

**Comment by gort818** [comment]
@omni6 It now launches at maximum window size at launch similar to a web browser.

**Comment by omni6** [comment]
my browser doesnt start maximized, it starts same position and size as i closed it. 
really this isnt common.

**Comment by gort818** [comment]
Yeah I can do that, just didn't quite understand.

**Comment by gort818** [comment]
@omni6 @navdeepio Ok just fixed this your window size will save when you exit.
https://github.com/gort818/qtwebflix/commit/862c167fd124476b702e18ac668405b98323f94a

Thanks a lot guys

**Comment by gort818** [comment]
Can you guys give this a test before I close it?

**Comment by omni6** [comment]
very, very nice!

**Comment by navdeepio** [comment]
working great!

On a side note, I'm unable to maximize the player..

**Comment by omni6** [comment]
F11
