### ISSUE TITLE
Core File will not be generated.

### ISSUE THREAD

**Issue by amoksito** [gort818/qtwebflix#21]
I cannot run the app. I'm using Arch Linux. 

Please help! This is the error:

[0502/034128.328556:WARNING:stack_trace_posix.cc(648)] Failed to open file: /home/emiliano/#6102056 (deleted)
  Error: No existe el fichero o el directorio
[21337:21364:0502/034128.386524:ERROR:gl_implementation.cc(246)] Failed to load /usr/bin/libGLESv2.so: /usr/bin/libGLESv2.so: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.10.1 Chrome/61.0.3163.140 Safari/537.36"
false
[21337:21364:0502/034128.520052:ERROR:gl_surface_qt.cpp(701)] Requested OpenGL implementation is not supported. Implementation: 0
*** stack smashing detected ***: <unknown> terminated
Received signal 6
#0 0x7fef25e4ee76 <unknown>
#1 0x7fef24acc88c <unknown>
#2 0x7fef25e4f1ec <unknown>
#3 0x7fef223aa8e0 <unknown>
#4 0x7fef223aa860 __GI_raise
#5 0x7fef223abec9 __GI_abort
#6 0x7fef223ed437 __libc_message
#7 0x7fef2247d39f __GI___fortify_fail_abort
#8 0x7fef2247d362 __stack_chk_fail_local
#9 0x7fef24b234cc <unknown>
#10 0x7fef2689a427 <unknown>
#11 0x7fef268a760e <unknown>
#12 0x7fef268a9eef <unknown>
#13 0x7fef268ab15f <unknown>
#14 0x7fef268a494d <unknown>
#15 0x7fef268a51d8 <unknown>
#16 0x7fef268a425e <unknown>
#17 0x7fef268a6885 <unknown>
#18 0x7fef25ed4c32 <unknown>
#19 0x7fef25e6c288 <unknown>
#20 0x7fef25e6d268 <unknown>
#21 0x7fef25e6d6d3 <unknown>
#22 0x7fef25e6ea31 <unknown>
#23 0x7fef25e8cf6b <unknown>
#24 0x7fef25ea7f46 <unknown>
#25 0x7fef25ea313b <unknown>
#26 0x7fef212dd08c start_thread
#27 0x7fef2246be7f __GI___clone
  r8: 0000000000000000  r9: 00007fee9f7fc730 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007fee9f7fc9d0 r13: 0000000000001000 r14: 0000000000000000 r15: 0000000000000030
  di: 0000000000000002  si: 00007fee9f7fc730  bp: 00007fee9f7fcb60  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fef223aa860  sp: 00007fee9f7fc730
  ip: 00007fef223aa860 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

**Comment by gort818** [comment]
Did qtwebflix work for you before or is this your first run of the program? Did you update recently?

**Comment by gort818** [comment]
Are you using wayland?
I found this https://bugs.archlinux.org/task/57018
Seems to have been fixed on 17 January 2018,, when did you last run an update on arch?

**Comment by omni6** [comment]
> /usr/bin/libGLESv2.so: /usr/bin/libGLESv2.so:

wrong path, here are mine

./usr/lib32/libGLESv2.so.2.0.0
./usr/lib32/libGLESv2.so
./usr/lib32/libGLESv2.so.2
./usr/lib/libGLESv2.so.2.0.0
./usr/lib/libGLESv2.so
./usr/lib/libGLESv2.so.2

Maybe there is something odd with you opengl, i would try to reinstall `libglvnd`, this package contains the libGLESv2. I guess run `sudo ldconfig` can do no harm.

**Comment by gort818** [comment]
@omni6 yeah it is searching for libs in the wrong path.. should be fixed on arch linux.
Here is the upstream from qt looks like it is getting fixed in qt 5.11
https://bugreports.qt.io/browse/QTBUG-65682

@amoksito  I think an update should fix your issue, and please tell me your qtwebengine version number and if you are runing wayland.

**Comment by gort818** [comment]
Closing for not enough info
