### ISSUE TITLE
Cadmium-playercore needs update

### ISSUE THREAD

**Issue by omni6** [gort818/qtwebflix#23]
Since yesterday netflix shows only loading circle... 
I think the new version of [cadmium-playercore](https://github.com/truedread/netflix-1080p) fixes this.

**Comment by gort818** [comment]
Thanks! Done :)

**Comment by omni6** [comment]
Hi gort,

as of today my netflix stopped working, get netflix error code 123xyzblah. Nothing changed so far on my system, i guess there's another update of the playercore needed. Truedreads version is now `cadmium-playercore-6.0009.457.011-1080p`

Anyway this couldn't harm to adopt...

**Comment by gort818** [comment]
I tried this to no avail, the author has modified it with "Edge manifest"  and I can no longer get it work :(
I will try a few more things but I think we will not have any more HD :(

**Comment by gort818** [comment]
Nevermind I got it! :)

Will update shortly

**Comment by gort818** [comment]
ok done, recompile and you are good to go

**Comment by omni6** [comment]
Brilliant, thank you! Is this now futureproof or must we be afraid of the next adjustment of playercore? Don't know what "Edge Manifest" is, got just Microso*t shit when i searched for...

**Comment by gort818** [comment]
Unfortunately it is not future proof , the author of the 1080p netflix extension added the edge manifest fix, and I cannot make it compatible so I had to edit the playercore script myself.

Hopefully in the future we will have HD natively.
