### ISSUE TITLE
qtwebflix possible incompatibility with qt5-webengine-widevine 1:66.0.3359.181-1

### ISSUE THREAD

**Issue by ryanmusante** [gort818/qtwebflix#25]
After upgrading qt5-webengine-widevine (1:66.0.3359.181-1), now qtwebflix has the error "missing component we cannot find all the required components to play netflix on this device".

**Comment by gort818** [comment]
I will look into this, what version of qtwebengine are you on?

**Comment by ryanmusante** [comment]
qt5-webengine-widevine 1:66.0.3359.181-1 from AUR. I wanted to downgrade but I don't keep cache from previous boots.

**Comment by gort818** [comment]
Not the aur package, but qt5-webengine version.

**Comment by ryanmusante** [comment]
qtwebflix[2752]: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.10.1 Chrome/61.0.3163.140 Safari/537.36"

**Comment by gort818** [comment]
or you can just downgrade qt5-webengine-widevine , https://aur.archlinux.org/cgit/aur.git/snapshot/aur-2043e94c590ab6acc53ef26dce28203a2c50b319.tar.gz

**Comment by ryanmusante** [comment]
Manjaro stable is a bit behind the releases in Arch repository. I'll downgrade the widevine for now, thank you.

**Comment by gort818** [comment]
No problem! If you need any more help let me know!

**Comment by ryanmusante** [comment]
I switched to manjaro unstable, grabbed qt5-webengine 5.11.0-2 along with updates and switched back to stable. Good to go.
