### ISSUE TITLE
player not working

### ISSUE THREAD

**Issue by ardadem** [gort818/qtwebflix#27]
i installed from arch aur and player always get to me M7702-1003 error.

**Comment by ardadem** [comment]
same with
```
qtwebflix --register-pepper-plugins="/usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so; application/x-ppapi-widevine-cdm"
```
btw

**Comment by gort818** [comment]
What distro are you running?

What version of qt5-webengine do you have installed?

**Comment by ardadem** [comment]
arch os
qt5-webengine auto installed from dependency: https://www.archlinux.org/packages/extra/x86_64/qt5-webengine/

**Comment by gort818** [comment]
Hmm I cannot reproduce,
What version of qt5-webengine-widevine do you have installed?

**Comment by ardadem** [comment]
here is the pkgbuild

```
pkgname=qt5-webengine-widevine
pkgdesc='A browser plugin designed for the viewing of premium video content'
pkgver=61.0.3163.100
_widevine_ver=1.4.8.1008
pkgrel=2
epoch=1
arch=('x86_64')
url='http://www.google.com/chrome'
license=('custom:chrome')
options=('!strip')
depends=('qt5-webengine')
source=(
"https://archive.archlinux.org/packages/c/chromium/chromium-${pkgver}-1-x86_64.pkg.tar.xz"
"https://dl.google.com/widevine-cdm/${_widevine_ver}-linux-x64.zip"
"chrome-eula_text.html::https://www.google.com/intl/en/chrome/browser/privacy/eula_text.html"
)
sha256sums=(
'5d4380308b3d5c2bc6e13d77090688ba00f0828f2777d83376d44038a6d0e2dd'
'fe04a5b56eac6674f1eda2c8eb28a0183ec1a66d80f72db618291e33078eb17d'
'SKIP'
)

package() {
install -Dm644 libwidevinecdm.so -t "$pkgdir/usr/lib/qt/plugins/ppapi/"
install -Dm644 usr/lib/chromium/libwidevinecdmadapter.so -t "$pkgdir/usr/lib/qt/plugins/ppapi/"
install -Dm644 chrome-eula_text.html -t "$pkgdir/usr/share/licenses/$pkgname/"
}
```

**Comment by gort818** [comment]
Ok that is the issue you should be on qt5-webengine-widevine 1:66.0.3359.181-1

**Comment by ardadem** [comment]
well, that chrome version url down

**Comment by gort818** [comment]
Well that sucks, I will try and find a solution

**Comment by omni6** [comment]
first i would write an AUR comment on [qt5-webengine-widevine](https://aur.archlinux.org/packages/qt5-webengine-widevine).
I have the package in my cache i offer you to download it from my Nextcloud: https://omnisome.ddns.net/index.php/s/q5HYzkAXi4npZRb

but really: report it!

**Comment by gort818** [comment]
I posted this on qt5-webengine-widevine aur package

we can grab ibwidevinecdmadapter.so.from here http://security.debian.org/debian-security/pool/updates/contrib/c/chromium-browser/chromium-widevine_66.0.3359.117-1~deb9u1_arm64.deb and libwidevinecdm.so from here https://dl.google.com/widevine-cdm/1.4.9.1088-linux-x64.zip

Not sure if the maintainer is active

**Comment by gort818** [comment]
I found this we extract the libwidevinecdmadapter.so
https://www.slimjet.com/chrome/download-chrome.php?file=lnx%2Fchrome64_66.0.3359.181.deb

**Comment by gort818** [comment]
The package maintainer updated qt5-webengine-widevine. Should be good to go!

**Comment by ardadem** [comment]
Oh, thanks for help guys!
