### ISSUE TITLE
Error Code: M7363-1260-00000048

### ISSUE THREAD

**Issue by Nuc1eoN** [gort818/qtwebflix#29]
When I want to playback a video I get the error in the title.
```
$ qtwebflix --register-pepper-plugins="/usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so; application/x-ppapi-widevine-cdm"
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.11.1 Chrome/65.0.3325.230 Safari/537.36"
Changing user agent to Firefox 57
false
Netflix Player detected! Injecting Netflix 1080p Unlocker...
```

Using ArchLinux

**Comment by gort818** [comment]
What distro are you using?

**Comment by gort818** [comment]
I have update the playercore, give that a try and see if it helps.

**Comment by bdutro** [comment]
Same problem here on arch 4.17.14 with latest master.

**Comment by gort818** [comment]
This is concerning, can someone test this branch https://github.com/gort818/qtwebflix/tree/non-hd

**Comment by bdutro** [comment]
The non-hd branch fixes the error, but I'm stuck on 720p at most (depending on the video - some are only 480p).

**Comment by gort818** [comment]
Ok thanks, now I know there is nothing wrong with widevine, it is the playercore that is not working, unfortunately I do not maintain that extension https://github.com/truedread/netflix-1080p. The recent update does not work with qtwebflix.

I hope to find a solution.

**Comment by bdutro** [comment]
Ah, yeah, that extension hasn't been working for me either.

**Comment by gort818** [comment]
@bdutro what browser did you try the extension with? You should report an issue on his repo.

**Comment by bdutro** [comment]
Chrome, and I've tried a Firefox extension based off of that repo that didn't work either. I should note that I actually get a different error using the extension (see https://github.com/truedread/netflix-1080p/issues/20) and only on certain titles. But qtwebflix fails on every title I try.

**Comment by bdutro** [comment]
So, the issue with the netflix-1080p extension was because of a script blocker.

...and now qtwebflix works too. Any idea how the two could be connected? Does qtwebflix pick up Chrome extensions or something?

**Comment by bdutro** [comment]
Yep, master branch works like a charm now.

**Comment by gort818** [comment]
Awesome that is good news, I wonder if anyone else is still having a problem. Thanks for your feedback!

**Comment by SpatiumPrinceps** [comment]
Hey, 
still getting this error (same log as above). Using the latest version from AUR from 3 days ago. 
Arch 4.17.14-arch1-1-ARCH
Any ideas?
Thank you already for taking care over this project :)

**Comment by SpatiumPrinceps** [comment]
qt5-webengine-widevine 1:66.0.3359.181-2 
should be the latest one from AUR aswell

**Comment by gort818** [comment]
I am not sure what is causing this, I have been getting mixed results with users on running the same system.
@omni6 Have you had any issues lately?

**Comment by omni6** [comment]
Sorry for the late answer, had no issues. Not before or after you updated the playercore . But followed the aur comments in qt5-webengine-widevine and therefor i hadn't updated it yet...

**Comment by omni6** [comment]
mhh... chromium-widevine and qt5-webengine-widevine have no `conflicts=` array in their pkgbuilds, it is possible to install both of them at one time.  You would have two different versions of the widevine libs because of different sources... just my thoughts. And when you have just chromium-widevine installed qtwebflix would't load widevine-libs because i have set `--register-pepper-plugins="/usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so` in the .desktop file

@SpatiumPrinceps can you exclude this cases?

**Comment by grisher** [comment]
I'm having this issue on Arch (4.17.14-arch1-1-ARCH) with webengine-widevine-1:66.0.3359.181-2.

**Comment by gort818** [comment]
Try removing the cache directory for qtwebflix see if that helps.
~/.cache/qtwebflix/QtWebEngine/Default/Cache

**Comment by godofgrunts** [comment]
Same issue here. Just updated everything today before installing so I have the latest of everything. I tried removing my cache as well, but it didn't help.

```
qtwebflix 
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.11.1 Chrome/65.0.3325.230 Safari/537.36"
Changing user agent to Firefox 57
false
Netflix Player detected! Injecting Netflix 1080p Unlocker...
Netflix Player detected! Injecting Netflix 1080p Unlocker...
```

**Comment by grisher** [comment]
@gort818 Removing the cache didn't help.

**Comment by jacob-swenson** [comment]
Also seeing this issue on Arch. Is there a temporary workaround or anything I can do to help debug?

**Comment by gort818** [comment]
I also reverted the change to the user agent if someone can give this a try and let me know.

**Comment by SpatiumPrinceps** [comment]
I was cleaning up my arch yesterday and found a nvidia driver blob although I disabled and never use the gpu. Removed the driver and qtwebflix loads just fine.

**Comment by gort818** [comment]
Anyone else still having issues with this?

**Comment by MaximilianoRom7** [comment]
I have the same issue on arch 4.14, I installed the package from AUR
Then I tried changing the PKGBUILD to checkout the branch non-hd and that solved the problem.

**Comment by gort818** [comment]
I have recently updated the playercore, if anyone still having issues can test the latest master and let me know.

**Comment by pamposzek** [comment]
After trying to launch a Netflix video, I'm getting "Unexpected Error" without any code. Using freshly updated version from the AUR (4.18.16).

**Comment by gort818** [comment]
@pamposzek can you trying deleting the cache folder it should be ~/.cache/qtwebflix

**Comment by pamposzek** [comment]
@gort818 Did that, unfortunately it didn't seem to help. The program seemed to remember my last played video and didn't demand re-logging at all, is it intended behavior even after deleting cache folder?

**Comment by gort818** [comment]
@pamposzek try deleteing ~/.local/share/qtwebflix/QtWebEngine/Default

**Comment by gort818** [comment]
@pamposzek it was working they seemed to have changed something... will report my findings

**Comment by gort818** [comment]
@pamposzek uploading the fix in a few minutes!

**Comment by gort818** [comment]
Narcos in 1080p on arch
![screenshot_20181116_163830](https://user-images.githubusercontent.com/9098121/48654002-1a5a8c80-e9be-11e8-9ed7-5f8273dd39a3.png)

**Comment by pamposzek** [comment]
Updated it with AUR now. Seems to work! However, by launching Test Patterns on Netflix, I can see only 1280x720, also seems to look that way in the actual movie. If it works for you, then it has to be something on my end, right?
![deepinscreenshot_qtwebflix_20181117021336](https://user-images.githubusercontent.com/42558876/48654590-7c42e280-ea0e-11e8-97ed-33cafe67f1aa.png)

**Comment by gort818** [comment]
Not all movies and shows will be in HD unfortunately, for test patterns wait a few minutes and see if it changes.

**Comment by pamposzek** [comment]
Numbers don't lie I guess... testing pattern sucks, but it changed properly in the movie. It's a proof it works! Big thanks for fixing it! My bitrate seems lower than yours (mine is 5620), but 1080p is 1080p (Also tested on opening of new Narcos series). When pressing ctrl+alt+shift+s, I couldn't see 7150 option you seem to have.
![deepinscreenshot_qtwebflix_20181117025518](https://user-images.githubusercontent.com/42558876/48655198-58829b00-ea14-11e8-93ea-e312604fbc3f.png)

**Comment by Nuc1eoN** [comment]
Thanks @gort818 and all the others for testing too! Just retested and the issue is definately fixed :)
I think I can close this bugreport then right? Yay!
