### ISSUE TITLE
Periodic drop-out and error message

### ISSUE THREAD

**Issue by sebiimaks** [gort818/qtwebflix#3]
When I open a video, it usually works for a little while, and then it drops out with "Error code: M7361-1253". A quick web search reveals a connectivity issue of some sort. It works fine through a web browser. I'm currently on Gnome 3 Antergos.

**Comment by omni6** [comment]
And i thought i am the only one having this issue [crashes from time to time](https://github.com/gort818/qtwebflix/issues/1). I guess its a kind of **caching issue**, when you skip to another position and back it works again... sometimes i need to load another movie first. This issue is qtwebflix exclusive, qupzilla or qutebrowser aren't affected and they use the same widevine libs. 
As i was the only one so far, i thought it could be an issue with my exotic filesystem (using NILFS)....

**Comment by sebiimaks** [comment]
Hmm, well I don't have any option to skip. I have to click back and then reload. It's really so frequent that I gave up using it.

**Comment by gort818** [comment]
I really wish I knew why this what happening, I will investigate and let you know of my findings.

@omni6 You might be right about caching .. hmm ok let's see what I can come up with.

**Comment by gort818** [comment]
@sebiimaks @omni6 There was a recent update to Qt, are you guys still having this issue?

I still haven't had any luck yet.

**Comment by omni6** [comment]
good point, i am always looking forward to a qt update that solve this issue. but the last did not, sorry.

**Comment by gort818** [comment]
@omni6 I am going to set up a test branch this week, if you don't mind testing it for me as it works on all my machines without a hitch.

**Comment by omni6** [comment]
when i compile qtwebflix with
qmake -config debug



and push it through gdb i get this:

```
../../../../qtwebengine-everywhere-src-5.10.0/src/3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0025
Received signal 11 SEGV_MAPERR 000000000019
#0 0x7ffff2d76106 base::debug::StackTrace::StackTrace()
#1 0x7ffff19a224c base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7ffff2d7647c base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7fffeea8bda0 <unknown>
#4 0x7ffff3b38ab4 sandbox::CrashSIGSYS_Handler()
#5 0x7ffff3b40ab9 sandbox::Trap::SigSys()
#6 0x7fffeea8bda0 <unknown>
#7 0x7fffedecedca __GI___mremap
#8 0x7fffede55b70 mremap_chunk
#9 0x7fffede5b111 __GI___libc_realloc
#10 0x7fffd8b4f491 <unknown>
#11 0x7fffd8b50878 <unknown>
#12 0x7fffd8b4e910 <unknown>
#13 0x7fffd8b4e400 <unknown>
#14 0x7fffd8b4e18d <unknown>
#15 0x7fffd8b3f17e <unknown>
#16 0x7fffd8b3edf4 <unknown>
#17 0x7fffd9042491 <unknown>
#18 0x7fffd9049f86 <unknown>
#19 0x7ffff4452aea ppapi::proxy::PPP_ContentDecryptor_Private_Proxy::OnMsgDecryptAndDecode()
#20 0x7ffff445472e ppapi::proxy::PPP_ContentDecryptor_Private_Proxy::OnMessageReceived()
#21 0x7ffff43f7a9b ppapi::proxy::PluginDispatcher::OnMessageReceived()
#22 0x7ffff36b0423 IPC::ChannelProxy::Context::OnDispatchMessage()
#23 0x7ffff2dfbf62 base::debug::TaskAnnotator::RunTask()
#24 0x7ffff2d935c8 base::MessageLoop::RunTask()
#25 0x7ffff2d945a8 base::MessageLoop::DeferOrRunPendingTask()
#26 0x7ffff2d94a13 base::MessageLoop::DoWork()
#27 0x7ffff2d95d71 base::MessagePumpDefault::Run()
#28 0x7ffff2db42ab base::RunLoop::Run()
#29 0x7ffff2d39bcb content::PpapiPluginMain()
#30 0x7ffff2d3eaca content::RunZygote()
#31 0x7ffff2d3edc0 content::ContentMainRunnerImpl::Run()
#32 0x7ffff3b4960e service_manager::Main()
#33 0x7ffff2d3db74 content::ContentMain()
#34 0x7ffff1a0233d QtWebEngine::processMain()
#35 0x555555554a15 <unknown>
#36 0x7fffeddf8f4a __libc_start_main
#37 0x555555554a6a <unknown>
  r8: 000000000000c0c0  r9: 00007fffedf0f410 r10: 00007fffffffad60 r11: 3030303030307830
 r12: 00007fffffffae04 r13: 00007fffffffaf00 r14: 00007fffffffae40 r15: 00005555557cd1a0
  di: 0000000000000001  si: 00007fffffffacc0  bp: 00007fffffffae40  bx: 0000000000000019
  dx: 0000000000000000  ax: 0000000000000019  cx: c000c0c000000000  sp: 00007fffffffae00
  ip: 00007ffff3b38ab4 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000019
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[23773:23982:1220/001729.893509:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"DecryptingVideoDecoder: decode error"}
[23773:23982:1220/001729.893627:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"video decode error"}
[23773:23773:1220/001729.894259:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR PIPELINE_ERROR_DECODE
```

**Comment by omni6** [comment]
omf... 
`../../../../qtwebengine-everywhere-src-5.10.0/src/3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0025
Received signal 11 SEGV_MAPERR 000000000019`
very suspicious....

...tried
`netflix --no-sandbox` works!

**Comment by omni6** [comment]
@sebiimaks 
could you try please?

**Comment by sebiimaks** [comment]
I received error code M7361-1253. It crashed with:

> qt5ct: using qt5ct plugin
> [18788:18806:1220/204638.028095:ERROR:service_manager.cc(156)] Connection InterfaceProviderSpec prevented service: content_plugin from binding interface: memory_instrumentation::mojom::Coordinator exposed by: content_browser
> ../../../../qtwebengine-everywhere-src-5.10.0/src/3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0025
> Received signal 11 SEGV_MAPERR 000000000019
> #0 0x7fe4e1959086 <unknown>
> #1 0x7fe4e05851cc <unknown>
> #2 0x7fe4e19593fc <unknown>
> #3 0x7fe4df41a8e0 <unknown>
> #4 0x7fe4e271ba34 <unknown>
> #5 0x7fe4e2723a39 <unknown>
> #6 0x7fe4df41a8e0 <unknown>
> #7 0x7fe4df4dcdca __GI___mremap
> #8 0x7fe4df463b70 mremap_chunk
> #9 0x7fe4df469111 __GI___libc_realloc
> #10 0x7fe4c871e491 <unknown>
> #11 0x7fe4c871f878 <unknown>
> #12 0x7fe4c871d910 <unknown>
> #13 0x7fe4c871d400 <unknown>
> #14 0x7fe4c871d18d <unknown>
> #15 0x7fe4c870e17e <unknown>
> #16 0x7fe4c870ddf4 <unknown>
> #17 0x7fe4c8c11491 <unknown>
> #18 0x7fe4c8c18f86 <unknown>
> #19 0x7fe4e3035a6a <unknown>
> #20 0x7fe4e30376ae <unknown>
> #21 0x7fe4e2fdaa1b <unknown>
> #22 0x7fe4e22933a3 <unknown>
> #23 0x7fe4e19deee2 <unknown>
> #24 0x7fe4e1976548 <unknown>
> #25 0x7fe4e1977528 <unknown>
> #26 0x7fe4e1977993 <unknown>
> #27 0x7fe4e1978cf1 <unknown>
> #28 0x7fe4e199722b <unknown>
> #29 0x7fe4e191cb4b <unknown>
> #30 0x7fe4e1921a4a <unknown>
> #31 0x7fe4e1921d40 <unknown>
> #32 0x7fe4e272c58e <unknown>
> #33 0x7fe4e1920af4 <unknown>
> #34 0x7fe4e05e52bd QtWebEngine::processMain()
> #35 0x55ccc9d80985 <unknown>
> #36 0x7fe4df406f4a __libc_start_main
> #37 0x55ccc9d809da <unknown>
>   r8: 00007ffd9d9b46e0  r9: 00007ffd9d9b46c0 r10: 00007ffd9d9b46a0 r11: 00007ffd9d9b4680
>  r12: 00007ffd9d9b4744 r13: 00007ffd9d9b4840 r14: 00007ffd9d9b4780 r15: 000055ccca22b950
>   di: 0000000000000001  si: 00007ffd9d9b4600  bp: 00007ffd9d9b4780  bx: 0000000000000019
>   dx: 0000000000000000  ax: 0000000000000019  cx: 0000000000000010  sp: 00007ffd9d9b4740
>   ip: 00007fe4e271ba34 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
>  trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000019
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.
> [18812:18844:1220/204814.233818:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"DecryptingVideoDecoder: decode error"}
> [18812:18844:1220/204814.234141:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"video decode error"}
> [18812:18812:1220/204814.251151:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR PIPELINE_ERROR_DECODE

I can confirm that netflix --no-sandbox fixes the problem.

**Comment by omni6** [comment]
@sebiimaks 
btw which distro do you use?

**Comment by sebiimaks** [comment]
I would assume so. Especially if nobody has audited the code, which I doubt they have.

**Comment by omni6** [comment]
https://github.com/qutebrowser/qutebrowser/issues/3163

**Comment by omni6** [comment]
`netflix --disable-seccomp-filter-sandbox` should be more  decent

**Comment by gort818** [comment]
Do you guys build qt and qtwebengine from source or from the repo? Seems like other users of various qtwebengine applications and chromium have the same issue.. not exactly sure what causes it.

Strange that it works for me with no problem..

>  --disable-seccomp-filter-sandbox
Looks like a great workaround until I can figure something out.

**Comment by omni6** [comment]
hey, i think this is the reason:
http://outflux.net/teach-seccomp/

for debugging i recompiled qtwebflix, plasma-desktop and plasma-workspace with debug options and installed qt5-*-debug pkg's from unofficial repo.

**Comment by omni6** [comment]
> Strange that it works for me with no problem..

kernel? 

Linux-4.14.7-1 here

**Comment by gort818** [comment]
Not at home at the moment will check later, there might be conflicting lib with seccomp.

**Comment by omni6** [comment]
wat do you think, is it necessary to enable sandbox for this kind of application? its only job is to browse netflix content. maybe all further investigation is waste of time.... seems like the common solution is to disable fkn sandbox..

**Comment by gort818** [comment]
I am on the same kernel.

I do not think there will be any issue.. I'm mean we are already running DRM software :( you are right all it does is connect to netflix and that is all, it is a very simple program.. it uses qtwebengine which is basically chrome to render the webpage and display it in a window.

**Comment by omni6** [comment]
i think this can get closed.
