### ISSUE TITLE
Chose Playback Resolution

### ISSUE THREAD

**Issue by ronmurphy** [gort818/qtwebflix#33]
Before the Netflix 1080p unlocker add in, i really enjoyed this app on my Pi and old laptop.  However, with several other people in the house streaming, I would like to ask if it is possible, and can it be added in, a way to chose your resolution playback?  As odd as it sounds, I like 720p, and i can not find a way by a .conf file to specify what playback resolution.

**Comment by gort818** [comment]
I actually have a non-hd branch, https://github.com/gort818/qtwebflix/tree/non-hd

**Comment by gort818** [comment]
Now that I think about it, i should probably add that as command line option, but for the moment you can use the non-hd branch.

**Comment by Termuellinator** [comment]
just to be sure there is no error on my side: many movies only play in 480p due to missing hdcp with amdgpu, right?

**Comment by ronmurphy** [comment]
Yes.  It's odd, but that's how it is

**Comment by gort818** [comment]
@ronmurphy I have added a command line option to disable the 1080p option on the latest master

**Comment by gort818** [comment]
added in 259397d7b0fe01b86bdfe5d7b7e8067961673771
