### ISSUE TITLE
How to get choice between Hulu and Netflix on launch?

### ISSUE THREAD

**Issue by Dzyn641** [gort818/qtwebflix#35]
I added hulu to the providers.conf but still can't figure out how to switch from Netflix to Hulu. I'm using i3wm can anybody help me out?

**Comment by gort818** [comment]
Just right click anywhere in the window and it should bring up the providers menu.

**Comment by omni6** [comment]
afaik i3 users don't use mouse..

**Comment by Dzyn641** [comment]
I logged into my Plasma session and still can't get the option

**Comment by gort818** [comment]
Are you using the latest build? Also if you are playing a video on netflix you cannot right click, you must return the main page and then right click anywhere.

**Comment by Dzyn641** [comment]
I'm using "qtwebflix-git 0.1.r48.g0f766ac-1" from the AUR, I'm also running Manjaro.

**Comment by gort818** [comment]
Can you right click in any other browsers? Qtwebflix should work just the same.

Can I see your Providers.conf file

**Comment by gort818** [comment]
I just updated a test branch adding command line options
```
Options:
  -h, --help                   Displays this help.
  -v, --version                Displays version information.
  -p, --provider <provider>    Set content provider eg. netflix.com
  -u, --useragent <useragent>  change useragent eg. "Mozilla/5.0 (Windows NT
                               10.0; WOW64) AppleWebKit/537.36 (KHTML, like
                               Gecko) Chrome/67.0.2526.73 Safari/537.36"
```


https://github.com/gort818/qtwebflix/tree/commandline

```
./qtwebflix -p hulu.com
```

**Comment by gort818** [comment]
cannot reproduce.
