### ISSUE TITLE
Window resizes after exiting fullscreen

### ISSUE THREAD

**Issue by Termuellinator** [gort818/qtwebflix#36]
When i leave Fullscreen, the Window resizes from maximised to a pretty small (i would say around 500px) window in the upper left corner. I'm on Manjaro KDE.

**Comment by gort818** [comment]
I will test this today, when  you resize your window before entering fullscreen, and then exit fullscreen is it still a small window? Your window size should be saved.

**Comment by gort818** [comment]
I tested and cannot reproduce your issue.

**Comment by gort818** [comment]
I am guessing we can close this? If not let me know.

**Comment by Termuellinator** [comment]
i wasn't able to test too much in the passing weeks, but the few times i did it seemed to work, lets hope for the best :)
