### ISSUE TITLE
Missing component - Error Code: F7702-1003

### ISSUE THREAD

**Issue by Saroumane** [gort818/qtwebflix#37]
**What I did :**
$ sudo apt-get install qtwebengine5-dev
$ git clone https://github.com/gort818/qtwebflix
$ cd qtwebflix/
$ chmod +x widevine.sh
$ sudo ./widevine.sh
$ qmake -config release
$ make

No errors so far...

**What I got :** 
qtwebflix starts normally, I can login, I can even see the first seconds of a movie when I'm on its page. But when I try to start a movie for real I get : 
"Missing component
We cannot find all the required components to play Netflix on this device. Please visit chrome://components, locate the WidevineCdm component, and click the "Check for update" button.
Error Code: F7702-1003"

Same result with 
$ qtwebflix --register-pepper-plugins="/usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so; application/x-ppapi-widevine-cdm"

Xubuntu 18.10   with qtwebengine5-dev  version 5.11.1
Chromium is installed : version 70.0.3538.77

**Comment by gort818** [comment]
Sorry haven't been keeping up to date on Ubuntu releases,
>qtwebengine5-dev version 5.11.1
I need to create a new script for widevine for Ubuntu 18.10 users.

Thanks for the issue!

**Comment by gort818** [comment]
Wrote a quick bash script please give it a try.

https://gist.github.com/gort818/524f6d2977d8a268cec357eb2c002825

**Comment by Saroumane** [comment]
Well done, it works !

Irrelevant question : when I do Control + Alt + Shift + D : I have statistics, but the Framerate says "NaN" (Not a Number I guess)
I tried qtwebflix because I was desperately looking for a Netflix that displays original framerate of Netflix shows. 
At least your app unlock 1080p on Linux, and that's a big bonus ! (Chromium/Firefox extension didn't worked for me)
