### ISSUE TITLE
Only 720p playback

### ISSUE THREAD

**Issue by Termuellinator** [gort818/qtwebflix#39]
As of this morning, QTWebflix will only show 720p :(
It seems the userAgent is blocked form 1080p, as my using firefox results in 1080p, but overriding useragent to "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.11.2 Chrome/65.0.3325.230 Safari/537.36" (as QTW seems to use, according to the shift+ctrl+alt+d overlay) also yields 720p.

Hate this BS from netflix -.-

**Comment by gort818** [comment]
I do not seem to have any issues.

![screenshot_20181202_121625](https://user-images.githubusercontent.com/9098121/49344458-43208a00-f62c-11e8-866a-088ad50c8584.png)

**Comment by Termuellinator** [comment]
so, i've now waited a full 24h since it occured again for me (and stayed that way) - can you reproduce it now? O_o

**Comment by gort818** [comment]
Working fine for me 
![screenshot_20181204_175713](https://user-images.githubusercontent.com/9098121/49485041-22079700-f7ee-11e8-9898-0588d5fea48e.png)

Note that some shows and movies 1080p will not be available, what are you trying to watch?

**Comment by Termuellinator** [comment]
![qtwebflix-720p](https://user-images.githubusercontent.com/22668785/49533854-65323a80-f8c0-11e8-92e3-3e3a16054306.png)
At least now it isn't fixed for me after your try ^^
It isn't the show, like i said it works fine in Firefox (with https://github.com/vladikoff/netflix-1080p-firefox that i think you use too?) as long as i use the FF63 UserAgent, if i set the UserAgent to "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.11.2 Chrome/65.0.3325.230 Safari/537.36", it also only gives me 720p, so it definitively is the UA. There has been a similar situation white FF61 (or was it 62?) where using the normal UA causes 720p, but setting it to the previous version worked fine - so to me it looks like netflix is filtering/blocking the UAs from getting HD. I'm just astounded that it works for you - maybe the filtering is not done on all series?
Does https://www.netflix.com/watch/80184619 give you 1080?

**Comment by gort818** [comment]
Can you try using the FF63 UA in qtwebflix?
I cannot test at the moment but I definitely will later today.

**Comment by gort818** [comment]
I just updated a test branch adding command line options
```
Options:
  -h, --help                   Displays this help.
  -v, --version                Displays version information.
  -p, --provider <provider>    Set content provider eg. netflix.com
  -u, --useragent <useragent>  change useragent eg. "Mozilla/5.0 (Windows NT
                               10.0; WOW64) AppleWebKit/537.36 (KHTML, like
                               Gecko) Chrome/67.0.2526.73 Safari/537.36"
```
https://github.com/gort818/qtwebflix/tree/commandline

./qtwebflix -u "Mozilla/5.0 (X11; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0"

**Comment by Termuellinator** [comment]
At least i learned how to clone a non-master-branch ^^
But it is just getting weirder.
For the show i linked above, the FF63 UA (the same i have in FF) doesn't change anything, still 720p.
I tested another one (black mirror), that one gives me 1080p with FF63 UA (both in QTW and FF) and with the new branch with default QTW UA (!), but only 720p with the normal QTW.
Additionally, using the QTW UA in FF no longer causes 720p on either of those shows.
So it kinda seems either something changed or my first test with setting the UA in FF was flawed.

**Comment by gort818** [comment]
The show you linked I am only getting 720p with FF63 ua and regular, Black mirror I get 720p with regular and 1080p with FF63 ua.

I have no idea. I actually cannot use that 1080p extension as it has extra stuff that I cannot implement.
I had to make my own changes.. It is a real pain.

I am worried that 1080p won't be around much longer for us.

look at this thread https://github.com/truedread/netflix-1080p/issues/30

**Comment by ryanmusante** [comment]
This is big corporate giving its' users the proverbial middle finger. Sad, but probably inevitable because it all comes down to money.

**Comment by gort818** [comment]
For the moment a lot of netflix originals are still 1080p but check messing around with different useragents and see which works best.

I do not know the must have some sort of deal with microsoft.. let's enjoy it while it lasts.

**Comment by ryanmusante** [comment]
@gort818 with Microsoft making plans to move Edge to being chromium based, would Edge come to Linux? And would the 1080p compatibility not be an issue?

**Comment by gort818** [comment]
@ryanmusante just read that article! was going to post a link https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/

Maybe should be interesting. Unless 1080p will only available on the windows10 app

**Comment by gort818** [comment]
I have updated the playercore again, might want to retest some videos.

**Comment by pamposzek** [comment]
Hey, suddenly it started working for me. Checked today on movie Killer Elite and it shows 1080p. Also on some kids cartoon too. From my perspective, it magically started working. Good stuff.

**Comment by Nuc1eoN** [comment]
Hey I am just watching netflix with the latest version and it seems I am also getting only 720p. Can I give you any other valuable info?

```
Version: 6.0011.853.051
Esn: NFCDFF-LX-EQ12YEM8R34FEHJQD0ECDY4MNPKUAU
PBCID: 6.iQtul7RYu_lMNUombYb9TqmYuSwV6Qo6nRMPz6zjTz4
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.3 Chrome/69.0.3497.128 Safari/537.36

MovieId: 70293591
TrackingId: 155573560
Xid: 15596969768980 (15596969768980)
Position: 832.961
Duration: 3598.000
Volume: 100%

Player state: Normal
Buffering state: Normal
Rendering state: Paused

Playing bitrate (a/v): 96 / 485 (1280x720)
Playing/Buffering vmaf: 90/90
Buffering bitrate (a/v): 96 / 485
Buffer size in Bytes (a/v): 3167678 / 10735264
Buffer size in Bytes: 13902942
Buffer size in Seconds (a/v): 240.105 / 247.034
Current CDN (a/v): c023.dus002.ix.nflxvideo.net, Id: 55725 / c023.dus002.ix.nflxvideo.net, Id: 55725

Audio Track: de, Id: A:1:1;2;de;0;, Channels: 2.0, Codec: audio/mp4;codecs=mp4a.40.2
Video Track: Codec: video/mp4;codecs=avc1.640028 (avchigh)
Timed Text Track: de, Profile: dfxp-ls-sdh, Id: T:1:0;1;de;1;1;

Framerate: NaN
Current Dropped Frames: 0
Total Frames: 12362
Total Dropped Frames: 1
Total Corrupted Frames: undefined
Total Frame Delay: undefined
Main Thread stall/sec: DISABLED
VideoDiag: readyState=4,currentTime=832.961314,pbRate=1,audioBuffered=48.000,audioRanges=816.853333-864.853332,videoBuffered=38.789,videoRanges=828.160666-866.949416,duration=3597.3855

Throughput: 70228 kbps

DFR: {"720":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}

```

**Comment by gort818** [comment]
@Nuc1eoN Damn netflix changed something again.. I will see if I can get it work again but I cannot promise anything :(

**Comment by gort818** [comment]
There was an update to widevine libs give it another test

**Comment by gort818** [comment]
I just tested Jessica Jones season 3 and after a few minutes I got 1080p.

**Comment by gort818** [comment]
see issue #72
