### ISSUE TITLE
Rawgit is shutting down

### ISSUE THREAD

**Issue by omni6** [gort818/qtwebflix#42]
As you can see [here](https://rawgit.com/).

https://github.com/gort818/qtwebflix/blob/a791f3ff147f468972f5c94d493e82735bdba94c/urlrequestinterceptor.cpp#L20

So we need to find another hosting service that works.. maybe this:

https://www.jsdelivr.com/rawgit

**Comment by gort818** [comment]
Already taken care of, that line is commented out.
