### ISSUE TITLE
Request disable netflix autopreview

### ISSUE THREAD

**Issue by ryanmusante** [gort818/qtwebflix#44]
Is this possible to incorporate? It is chrome compatiblity. 

> Harken back to the glory days of no weird hover states, autoplaying videos, and annoying Who's Watching prompts.

https://chrome.google.com/webstore/detail/netflix-classic/mokjkiliipanjhlfbpagnmlpihmaohde

**Comment by gort818** [comment]
I cannot implement extensions into qtwebengine, I might be able to disable the auto preview with javascript.. but I don't really know javascript sooo I'm not sure.

**Comment by gort818** [comment]
@ryanmusante Good news! figured it out  this is how it looks when you load netflix
![screenshot from 2019-01-03 14-51-31](https://user-images.githubusercontent.com/9098121/50665861-1df2a480-0f67-11e9-8a7a-0bcc7169b0c8.png)

**Comment by gort818** [comment]
I found a hacky solution that would work well with some cool new features coming.. stay tuned

**Comment by ryanmusante** [comment]
Sounds good!

**Comment by gort818** [comment]
```
QString code ="try { " \
                           "billboard = document.querySelector('.billboard-row');"\
                           "if (billboard) {" \
                           "var video = document.querySelector('video');" \
                           "video.muted = true;"\
                           "video.playbackRate = 0;"\
                           "video.setAttribute('preload', 0);"\
                           "video.setAttribute('autoplay', 'false');"\
                           "video.pause();"\
                           "}" \
                           "} catch (e) {  } " ;

             webView()->page()->runJavaScript(code);
```
This seems to work! it is not pretty but there will be no more autopreview crap

**Comment by gort818** [comment]
![netflix](https://user-images.githubusercontent.com/9098121/50678380-499b7c00-0fb3-11e9-90b0-a2b8661daa06.png)

Here is how it looks now just need to find a way for users to opt in.

**Comment by ryanmusante** [comment]
It works, simply amazing!

**Comment by gort818** [comment]
I think option 2 is the best just have a command line argument like -na for no auto play. Will work on this today, I'll let you know when it is ready.

**Comment by ryanmusante** [comment]
This makes use of command line arguments and uses qt web engine.
https://github.com/magiruuvelvet/LightweightQtDRMStreamViewer

**Comment by gort818** [comment]
@ryanmusante qtwebflix has command line arguments, just haven't implemented this yet sorry :( maybe this weekend

**Comment by ryanmusante** [comment]
Status update for feature implement?
