### ISSUE TITLE
Support for mpris interface

### ISSUE THREAD

**Issue by petrmanek** [gort818/qtwebflix#45]
I'm using QtWebFlix regularly now and I have a feature suggestion. It'd be awesome if QtWebFlix could support the [mpris D-Bus interface][1].

This would allow:

 - to play/pause video playback using tools like `playerctl` and media keys on the keyboard,
 - to rewind/fast forward video playback,
 - to adjust video volume,
 - to report currently playing video name in monitor bars.

[1]: https://specifications.freedesktop.org/mpris-spec/latest/

**Comment by omni6** [comment]
Would this give the ability to control with KDE-connect?

**Comment by petrmanek** [comment]
@gort818 I'd be happy to give you a hand. I just need to get a bit more familiar with the code base.

**Comment by petrmanek** [comment]
I found [this adaptor][1] for bridging mpris and Qt. Seems like the toughest part is going to be figuring out whether playback is going on and controlling it via JavaScript.

[1]: https://github.com/nemomobile/qtmpris

**Comment by petrmanek** [comment]
By quick examination of mainwindow.cpp and some fiddling around in my browser's dev console, I have made the following observations:

 - `document.querySelector('video')` can still be used access the HTML's `<video>` object.
 - The property `paused` can be used to check if the video is playing or not. If everything else fails, checking it once per second using e.g. `QTimer` can work nicely to determine the player's playback state.
 - If used properly, a JavaScript listener could be added to the `<video>` to notify the Qt program that player's playback state has changed. The only thing left to figure out is how to asynchronously signal a `QWebView` from JavaScript.
 - To play/pause the video, the functions `.play()` and `.pause()` can be used without problems.
 - To adjust volume, the property `volume` can be used with a float from 0 to 1. Netflix's UI seems to adjust automatically even when the volume is set from the console.
 - I don't know how to get the current playing video's name. This picture shows the DOM hierarchy, from which it may be extracted: https://gyazo.com/2f11b18ce79c05ef153d83073518c762

**Comment by petrmanek** [comment]
So, to showcase the referenced features I have created a simple [fork][1] of the repo. It can issue basic commands to the video player but still has no ties to mpris.

At the moment, I'm a bit hesitant about adding dependency on the D-Bus adapter I found, as it doesn't seem to be present as a package in any of the major Linux distributions. Does anyone have a better alternative?

[1]: https://github.com/petrmanek/qtwebflix

**Comment by omni6** [comment]
I can package it for arch, looks quite easy...

**Comment by omni6** [comment]
It will become a split package... we would need [qtmpris](https://github.com/nemomobile/qtmpris) and [qtdbusextended](https://github.com/nemomobile/qtdbusextended). So far no problem but atm a bit out of time... Will do this evening.

**Comment by omni6** [comment]
Ok, both packages build with no problems. Can immediately upload... you need it for develpment? Otherwise i would wait as long we need it as dependencie for qtwebflix...

**Comment by petrmanek** [comment]
@omni6 Cool, feel free to put them up to AUR.

**Comment by omni6** [comment]
https://aur.archlinux.org/packages/qt-dbus-extended-git/
https://aur.archlinux.org/packages/qt-mpris-git/

**Comment by omni6** [comment]
> Check out this commit. It can toggle play/pause and full screen and report back player state playing/paused/stopped. I have tested it and it seems to work nicely with playerctl.

Basic control from kdeconnect works, i can play/pause/resume. But it would be great if you can get the dead buttons to work. Don't know if that is possibe but instead of skip we could use that button for fast forward/backward. Picture of now playing movie would also be nice.

**Comment by petrmanek** [comment]
@omni6 Check it out, I've put up another iteration. This one should start animating the time bar in such a way that it's possible to see video duration and the current time position within the video.

Unfortunately, I've encountered difficulties when trying to set the time position within the video to absolute or offset values. Seems like Netflix has some sort of protective scripts which determine whether the position jumps suspiciously large intervals.

**Comment by gort818** [comment]
@petrmanek This is awesome! Unfortunately I do not know much about mpris, how would we support users of other distros? Could we make mpris a separate class, move it out from mainwindow? I think I know how to get the name of the video playing in netflix.

**Comment by gort818** [comment]
@petrmanek I was able to get the html of video title like this,

elem = document.querySelector('.PlayerControls--control-element.video-title .ellipsize-text ');
elem.innerHTML

Hope that helps!

**Comment by petrmanek** [comment]
@gort818 Glad you like it! 🎉

mpris itself is built on D-Bus, so most of the modern SystemD-powered distros are supported out of the box. In addition, popular WMs like KDE, Gnome, xfce or mate have mpris-capable widgets or sidebars, making it a really convenient feature.

Still, `qtmpris` and `qtdbusextended` can now be considered to be dependencies (or we can put some macro magic around them to make them optional).

For this reason, they either:

 1. need to be either included as a part of QtWebFlix's package, or
 2. need to be packaged on their own (like @omni6 did for arch's AUR) and be referenced, so that package managers will install them prior to QtWebFlix.

With regards to the code, the current state is rather experimental and temporary. It's definitely a good idea to move the mpris-specific additions out into a separate class / file. It'll however be necessary to expose mainwindow's web view, since the new class will want to run JavaScript commands on it.

Thanks for the suggestion concerning the title. I have already put it to use (see the latest commit). It seems to work nicely for movies. For TV shows it, however, concatenates the show's title with the episode name, like so:

    MythBustersS4:E15Steam Cannon

**Comment by gort818** [comment]
elem.innerHTML.replace(/(<([^>]+)>)/g, " ").replace(/ +(?= )/g,'').replace(/ +(?= )/g,'').trim();

**Comment by petrmanek** [comment]
@gort818 Nice, seems to work.

**Comment by gort818** [comment]
@omni6  
> Picture of now playing movie would also be nice.

I will try and see if I can get the thumbnail, no guarantees but that would be awesome.

**Comment by petrmanek** [comment]
@gort818 If you can get me a public URL of the thumbnail, I already have a mpris metadata key for it. ;)

**Comment by gort818** [comment]
@petrmanek I have noticed many other qt programs that use mpris without extra dependencies.

Here how it was implemented in babe https://github.com/KDE/babe/blob/master/src/kde/mpris2.h

**Comment by gort818** [comment]
I created a new branch with qtmpris and qtdbusextended incuded 

https://github.com/gort818/qtwebflix/tree/mpris

it will build the libs that way we dont have to worry about packaging it

**Comment by petrmanek** [comment]
@gort818 
**Ad thumbnail:** We don't need the actual data from the request. Just the URL is fine for mpris (it has a dedicated [ArtURL metadata key]). Can you retrieve that somehow? Also, I've noticed that the `<video>` object has a `poster` property which is supposed to contain a similar URL, perhaps that might help.

**Ad KDE/babe:** That would be my preference as well. Unfortunately, [the implementation][2] seems rather minimalistic. I've also found [a fork][3] of this repo, which attempted to support mpris. However, according to [issues][4] and the commit log, it seems like they didn't get too far implementation-wise. If you have any other suggestions, feel free to reference them -- I haven't found too many thus far.

**Ad branch:** Kudos to you if you actually got the project to build. I've attempted the same thing but rather unsuccessfully. Since they're both on GitHub, I'd definitely suggest including both libs as [submodules][5] instead of copy-pasting them into the repo. This way, we can keep up with any modifications in the future. I'd also prefer linking both libs statically to avoid any clashes in /usr/lib in distros (like arch), where you can install them independentely of QtWebFlix.

At the moment, I'm a bit at loss about where to continue the development of this feature. Should I give you permission to push to my fork? Would you rather prefer a pull request to the `mpris` branch? Or should I disregard the new branch for the moment and continue working on the fork, which we'll merge at a later time?

[1]: https://github.com/nemomobile/qtmpris/blob/master/src/mpris.h#L63
[2]: https://github.com/KDE/babe/blob/master/src/kde/mpris2.cpp
[3]: https://github.com/intersimone999/qtws
[4]: https://github.com/intersimone999/qtws/issues/1
[5]: https://git-scm.com/docs/git-submodule

**Comment by gort818** [comment]
thumbnail is a pain...

```
item= document.querySelector('video').offsetParent.id // gets us the title id
curl -i -H "Accept: application/json"  "https://www.netflix.com/title/80131551"  // get us json info
grep -Po 'image":.*?[^\\]",' text.txt   // gets us the image 
```

Hope that helps! now just to add it all to qt :)

I would say continue working on the fork, you can see use the mpris fork for reference to see how I built the libs and the executable if we go that route.

Thanks so much for your efforts I really like what you have done it is awesome!

**Comment by gort818** [comment]
Clementime player uses mpris you can check that one out.

also I see ubuntu has a package https://launchpad.net/ubuntu/+source/qtmpris/0.1.0-2

**Comment by gort818** [comment]
here is an idea to implement it...

```
 // get netflix title
   view->page()->runJavaScript(
        "document.querySelector('video').offsetParent.id",
        [](const QVariant &result){
            qDebug() << "Value is: " << result.toString() << endl;
        }
    );
 
   // using the title add it to 'https://www.netflix.com/title
    QProcess* proc = new QProcess();
    QString cmd( "/bin/sh" );
    QStringList args;
    args << "-c" <<"curl -s -i -H 'Accept: application/json'  'https://www.netflix.com/title/80131551' | grep -Po '\"image\": *\\K\"[^\"]*\"' ";
    proc->start(cmd, args);
    proc->QProcess::waitForFinished(-1);
    QString output(proc->readAll());
    output.remove(QRegExp("[\\n\\t\\r]"));
    output.remove(QRegExp("[^a-zA-Z:/.-\\d\\s]"));
    qInfo()<< output;
```

**Comment by petrmanek** [comment]
@gort818 Check it out! I've devised a pure Qt way of doing the same thing without having to launch another process and rely on curl and grep being installed.

The metadata now looks like this:

```bash
$ playerctl metadata
{'mpris:artUrl': <'https://occ-0-3141-2773.1.nflxso.net/art/4c566/9f9ff80dbad539bfced0e018edffe601a594c566.jpg'>, 'mpris:length': <int64 3016192000>, 'mpris:trackid': <objectpath '/com/netflix/title/70141922'>}
```

**Comment by gort818** [comment]
@petrmanek That is beautiful! Nicely done! Thanks so much!

@omni6 check it out!

**Comment by omni6** [comment]
![screenshot_trebuchet_20190101-200707](https://user-images.githubusercontent.com/24492439/50575763-870dd700-0e04-11e9-9281-c95b982a6324.png)
![screenshot_trebuchet_20190101-203447](https://user-images.githubusercontent.com/24492439/50575775-c50afb00-0e04-11e9-9c31-70edfecbd669.png)

**Comment by gort818** [comment]
Awesome looking good!

**Comment by petrmanek** [comment]
Sweet!

**Comment by gort818** [comment]
Here is how to get amazon prime video title 
```
document.querySelector('div.webPlayer').innerText.split('X')[0].trim()
```

**Comment by omni6** [comment]
Can arrow keys, enter and back get implemented?

**Comment by petrmanek** [comment]
@omni6 It all comes down to bypassing Netflix's protections. If you try to modify `<video>`'s position directly, it just redirects you to that error page.

Perhaps if instead we tried to simulate a click on the position bar, we could achieve the result without raising suspicions.

@gort818 Do you think we could find the position bar in the DOM tree?

**Comment by omni6** [comment]
I don't mean to modify the movie Position. This is meant to navigate on the streaming webpage.

**Comment by petrmanek** [comment]
I guess we could make prev/next navigate TV show episodes. However, I'm not sure how to get to their IDs (or URLs). Any suggestions?

**Comment by omni6** [comment]
Oh, i was sure about that it is possible to navigate with keyboard on the webpage. You know, with the arrow keys, enter and maybe escape/backspace for back and send this commands over mpris... but navigate with keyboard doesn't work.

**Comment by gort818** [comment]
@petrmanek 
try this
```
document.querySelector('div.PlayerControlsNeo__progress-control-row.PlayerControlsNeo__progress-control-row--row-standard')
```
No idea how to interact though

**Comment by gort818** [comment]
@petrmanek I got fast forward and backword... no seek yet :(
```
// fast forward
document.querySelector('button.touchable.PlayerControls--control-element.nfp-button-control.default-control-button.button-nfplayerFastForward').click()

//rewind
document.querySelector('button.touchable.PlayerControls--control-element.nfp-button-control.default-control-button.button-nfplayerBackTen').click()

```

**Comment by gort818** [comment]
@petrmanek and here is next epsidoe
```
document.querySelector('button.touchable.PlayerControls--control-element.nfp-button-control.default-control-button.button-nfplayerNextEpisode').click()
```

**Comment by gort818** [comment]
@petrmanek and here is the seek bar
```
document.querySelector('div.scrubber-bar')
```
Cannot find a way to intereact

**Comment by gort818** [comment]
@petrmanek and here is the back button maybe use it as stop ?
```
document.querySelector('button.touchable.PlayerControls--control-element.nfp-button-control.default-control-button.button-nfplayerBack.tooltip-button.tooltip-button-pos-center.tooltip-button-align-right').click()
``

**Comment by petrmanek** [comment]
@gort818 Wow, you've been busy! I'm going to put the code to a good use.

I was thinking about supporting multiple different services other than Netflix (like Amazon Prime, etc.), and I think there's a better solution than to basically have series of `if`'s or `switch`'s in every function.

Instead, I would propose to solve this by inheritance. Turn `MprisInterface` into an abstract interface, and then have the actual implementation present in `NetflixMprisInterface` and `PrimeMprisInterface` where it's safe to assume we're dealing with the single respective streaming service. This way we may also avoid branching the mpris logic the same way in every single function body.

The job of `MainWindow` would then be to communicate with `MprisInterface` and occasionally exchange it for other implementation when user switches services. What do you think about that?

P.S. I don't have Prime subscription, so you'll have to help me test those features.

**Comment by gort818** [comment]
@petrmanek Yeah that sounds good if we are going to support other services, I only have a netflix and prime account right now, so I guess when can start with those.

Also I thought about what you said earlier I will add the qt-mpris libs as submodules and compile them as static libraries I think that is the easiest solution, I will let you know when I have pushed to the mpris branch.

Again thanks for all your hard work I am loving it !

**Comment by gort818** [comment]
@petrmanek Ok got everything building with static libs https://github.com/gort818/qtwebflix/tree/mpris

I believe you just have to include the header files and you should be good to go!

**Comment by gort818** [comment]
@petrmanek nvm not working..

**Comment by gort818** [comment]
@petrmanek Ok I think it is good to go

**Comment by gort818** [comment]
@petrmanek Ok did a nice test was able to use mpris with no issues, the executable has doubled in size from 127K to 332K :) let me know if you have any issues

**Comment by petrmanek** [comment]
@gort818 trying now... will let you know how it went

**Comment by petrmanek** [comment]
@gort818 Are you sure it builds from the sources?

When I tried the same thing, it worked nicely until I uninstalled qtmpris and qtdbusextended packages in `/usr/lib/`. From that point on, it started complaining that

```Project ERROR: dbusextended-qt5 development package not found```

The build directory currently looks like this:

```
build
├── lib
│   ├── qtdbusextended
│   │   ├── Makefile.dbusextended-qt
│   │   └── src
│   │       ├── dbusextendedabstractinterface.o
│   │       ├── dbusextendedpendingcallwatcher.o
│   │       ├── dbusextended-qt5.prf
│   │       ├── libdbusextended-qt5.prl
│   │       ├── libdbusextended-qt5.so -> libdbusextended-qt5.so.1.0.0
│   │       ├── libdbusextended-qt5.so.1 -> libdbusextended-qt5.so.1.0.0
│   │       ├── libdbusextended-qt5.so.1.0 -> libdbusextended-qt5.so.1.0.0
│   │       ├── libdbusextended-qt5.so.1.0.0
│   │       ├── Makefile
│   │       ├── moc_dbusextendedabstractinterface.cpp
│   │       ├── moc_dbusextendedabstractinterface.o
│   │       ├── moc_dbusextendedpendingcallwatcher_p.cpp
│   │       ├── moc_dbusextendedpendingcallwatcher_p.o
│   │       ├── moc_predefs.h
│   │       └── pkgconfig
│   │           └── dbusextended-qt5.pc
│   └── qtmpris
│       ├── Makefile.mpris-qt
│       └── src
└── Makefile
```

To me, this suggests that `pkg-config` is does not see the `dbusextended-qt5.pc` file, and that's why the qtmpris target fails.

**Comment by petrmanek** [comment]
Victory! It took me a while (I'm not your regular QMake user) but I figured out how to do it.

So the current state of the fork is as follows:

 1. Repositories qtmpris and qtdbusextended are now referenced as submodules. For this reason, all package build files (bump @omni6) have to use `--recursive` when cloning QtWebFlix, otherwise the `lib/` directory will be left empty.
 2. I had to create patched .pro files for both libraries. Unfortunately, this was a necessary step in order to bypass `pkg-config` and build both libraries as static. Both configuration files can be found in the [lib/][1] directory along with their README.md -- they will have to be kept up-to-date with their counterparts in their respective repos.
 3. `qtwebflix.pro` was moved to `src/src.pro` and configured to link with the built libraries. The new `qtwebflix.pro` contains dependency information to ensure that the libraries get built ahead of the executable.
 4. The executable binary is now located in `src/qtwebflix` within the build directory and has grown to ~360 kB. It no longer requires qtmpris and qtdbusextended as runtime dependencies, since they are both linked statically.

Let me know if it works for you.

[1]: https://github.com/petrmanek/qtwebflix/tree/master/lib

**Comment by omni6** [comment]
the whole stuff is too fragmented... can we do a merge please?

For pkgbuild i think i found a solution to init the submodules:

```
source=("git://somewhere.org/something/something.git"
        "git://somewhere.org/mysubmodule/mysubmodule.git")

prepare() {
  cd something
  git submodule init
  git config submodule.mysubmodule.url $srcdir/mysubmodule
  git submodule update
}
```

**Comment by omni6** [comment]
feels strange to me... but works:

https://gist.github.com/omni6/ce287065d67a3a7faf2364020b96df68

**Comment by omni6** [comment]
[PKGBUILD](https://gist.github.com/omni6/52b0a7c052a7bd84209d88dd22faac68)

[MAKEPKG](https://gist.github.com/omni6/655c5f4874ce6147f297d8b2cd6a628b)

**Comment by petrmanek** [comment]
@omni6 Nice work!

In the meantime, I've refactored the code. We currently have `MprisInterface` base class which does the generic stuff and `NetflixMprisInterface` which contains JavaScripts and timers specific to Netflix.

This way, we can later add implementations for Amazon Prime, HBO Go, etc. and still have everything nicely organized.

**Comment by omni6** [comment]
No wait with honour... i haven't used your patched *.pro files. When i do i can't get a proper `make install` to work. Yes sure because of no pkgconfig... can we get a complete install rule when doing
`make -C ${srcdir}/src/src.pro  INSTALL_ROOT="${pkgdir}" install`

including: 

- binary
- libs
- .desktop
- qtwebflix.svg

?

**Comment by petrmanek** [comment]
@omni6 The libs are *not* required at runtime -- only at build time. So, you don't need to include them in the package.

You should be able to get everything just by executing the following commands in the project root:

```bash
mkdir build
cd build
qmake -c release ..
make
INSTALL_ROOT="${pkgdir}" make install
```

Disclaimer: I'm not sure how will handle the .desktop and .svg file.

**Comment by omni6** [comment]
i get this:
```
==> Entering fakeroot environment...
==> Starting package()...
cd lib/ && ( test -e Makefile.qtdbusextended || /usr/bin/qmake -o Makefile.qtdbusextended /tmp/makepkg/qtwebflix-git/src/qtwebflix/lib/qtdbusextended.pro -config release ) && make -f Makefile.qtdbusextended install
make[1]: Entering directory '/tmp/makepkg/qtwebflix-git/src/qtwebflix/build/lib'
make[1]: Nothing to be done for 'install'.
make[1]: Leaving directory '/tmp/makepkg/qtwebflix-git/src/qtwebflix/build/lib'
cd lib/ && ( test -e Makefile.qtmpris || /usr/bin/qmake -o Makefile.qtmpris /tmp/makepkg/qtwebflix-git/src/qtwebflix/lib/qtmpris.pro -config release ) && make -f Makefile.qtmpris install
make[1]: Entering directory '/tmp/makepkg/qtwebflix-git/src/qtwebflix/build/lib'
make[1]: Nothing to be done for 'install'.
make[1]: Leaving directory '/tmp/makepkg/qtwebflix-git/src/qtwebflix/build/lib'
cd src/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /tmp/makepkg/qtwebflix-git/src/qtwebflix/src/src.pro -config release ) && make -f Makefile install
make[1]: Entering directory '/tmp/makepkg/qtwebflix-git/src/qtwebflix/build/src'
make[1]: Nothing to be done for 'install'.
make[1]: Leaving directory '/tmp/makepkg/qtwebflix-git/src/qtwebflix/build/src'
==> Tidying install...

```

**Comment by omni6** [comment]
@petrmanek 
but when the libs are not required, i can use the old way and do it manually...
i will test...

**Comment by omni6** [comment]
here we go:
[PKGBUILD](https://gist.github.com/omni6/52b0a7c052a7bd84209d88dd22faac68)

**Comment by petrmanek** [comment]
@omni6 Seems nice. But we need to merge it to the base repo before going ahead with the release.

**Comment by omni6** [comment]
@petrmanek sure, this is for testing. Only thing to change is url

**Comment by omni6** [comment]
@petrmanek 
> Disclaimer: I'm not sure how will handle the .desktop and .svg file.

no worries, not a problem.

**Comment by gort818** [comment]
@petrmanek 
> 2. I had to create patched .pro files for both libraries. Unfortunately, this was a necessary step in order to bypass `pkg-config` and build both libraries as static. Both configuration files can be found in the [lib/](https://github.com/petrmanek/qtwebflix/tree/master/lib) directory along with their README.md -- they will have to be kept up-to-date with their counterparts in their respective repos.

Oops should have let you know that sorry!
Looking good, whenever you are ready to send a pull request send it on over.

A question though, how are you going to check which mpris interface to use? 

@omni6 package looks good I will let you know when we are go to go.

**Comment by petrmanek** [comment]
@gort818 Pull request [underway][1].

> A question though, how are you going to check which mpris interface to use?
MainWindow can switch interfaces based on the current URL's hostname in the QWebEngineView.

[1]: https://github.com/gort818/qtwebflix/pull/50

**Comment by gort818** [comment]
@petrmanek @omni6 
Thanks guys!
