### ISSUE TITLE
Lacking HiDPI screen support

### ISSUE THREAD

**Issue by olantrust** [gort818/qtwebflix#46]
The app is currently not honouring HiDPI settings.
This results in minute unviewable/unusable writing/menus/icons in the app.

Running: Manjaro KDE 18.0.1
Screen resolution: 3200 x 1800
Display scale set at x2 (in KDE settings)
![qtwebflix-hidpi](https://user-images.githubusercontent.com/627140/50530491-0d20d980-0af6-11e9-9edd-0242798da2dd.png)

**Comment by gort818** [comment]
Thanks for the issue, should be an easy fix.

**Comment by gort818** [comment]
can you try the latest commit and see if it fixed your issue?

**Comment by olantrust** [comment]
> can you try the latest commit and see if it fixed your issue?

Hi, thanks for the speedy response.
The icons now work, as per #47 
Alas, the HiDPI is still not working (or else not being detected), same result as attachments above.

**Comment by gort818** [comment]
I tested on my end and had no issues :( Have you tried a different website?

**Comment by olantrust** [comment]
> I tested on my end and had no issues :( Have you tried a different website?

Working fine now!
Not sure why not previously... but it's cool.

**Comment by gort818** [comment]
ok awesome! Glad it works!

**Comment by olantrust** [comment]
> I tested on my end and had no issues :( Have you tried a different website?

Alas, even with the changes, still 
![qtwebflix-hdpi-helpscreen-screenshot_20190103_155719](https://user-images.githubusercontent.com/627140/50647548-bf322880-0f70-11e9-8831-c7597858ab62.png)
![qtwebflix-hdpi-header-screenshot_20190103_155719](https://user-images.githubusercontent.com/627140/50647549-bfcabf00-0f70-11e9-8887-160af3229bce.png)

having more issues that I hadn't noticed.

So, with Netflix, but also with other sites (Amazon Prime Video, and Mubi.com) the main site content is scaled correctly, but the headers, and footers, and other contents (such as the Netflix Account and Help pages) are wrongly-scaled, and minute in appearance.

See attached.

**Comment by gort818** [comment]
Wow strange, I have no issues .. can you try QT_SCALE_FACTOR 2 qtwebflix

**Comment by olantrust** [comment]
> Wow strange, I have no issues .. can you try QT_SCALE_FACTOR 2 qtwebflix
Yeah that works! QT_SCALE_FACTOR=2 qtwebflix
