### ISSUE TITLE
Icon inconsistency

### ISSUE THREAD

**Issue by olantrust** [gort818/qtwebflix#47]
It would be great to improve the icons further:

1) The main icon shown (in the panel and app menu) could be a new icon for WebFlix - rather than the current Netflix icon?
![qtwebflix-icon1-screenshot_20181228_231801](https://user-images.githubusercontent.com/627140/50530691-e6fc3900-0af7-11e9-9acc-68ba8be2e078.png)

2) The icon appearing in the app window is an X icon rather than the program icon
![qtwebflix-icon2-screenshot_20181228_231801](https://user-images.githubusercontent.com/627140/50530690-e6fc3900-0af7-11e9-98f5-ac858460a974.png)

3) When switching between windows/tasks the X icon is shown, rather than the program icon
![qtwebflix-icon3-screenshot_20181228_231801](https://user-images.githubusercontent.com/627140/50530689-e663a280-0af7-11e9-8517-8fe1cef1358b.png)

**Comment by gort818** [comment]
Thanks!
Fixed with  4e5f2b0

**Comment by gort818** [comment]
I reread your issue , what do you mean in your first point?

**Comment by omni6** [comment]
@varlesh, my great master of icons!

> In the first point, I was querying whether the icon should be changed, something more neutral (to avoid copyright issues and also to as the app can access multiple providers, not just Netflix).

Are you willing to design a unique qtwebflix icon?

**Comment by varlesh** [comment]
@omni6 
example:
![image](https://user-images.githubusercontent.com/8083855/50574416-ba9b3200-0e01-11e9-85bf-4065458fec36.png)

**Comment by omni6** [comment]
@gort818 what are your thoughts?

I think it would be great if the grey background has the shape of a TV.. maybe something like this http://orig02.deviantart.net/84a9/f/2015/321/5/e/flat_retro_tv_vector_icon_by_superawesomevectors-d9h0oaf.jpg but more asymetric... oh, or like this one http://www.webertainment.de/images/screens/original/11359331052.jpg

**Comment by omni6** [comment]
@varlesh 
btw, glad you do it!

**Comment by varlesh** [comment]
@omni6 I try it... how about Q-logo?
![image](https://user-images.githubusercontent.com/8083855/50574637-a5280700-0e05-11e9-98eb-f8245927ea23.png)
**Q**t**W**ebFlix

**Comment by omni6** [comment]
nice one, but it is to @gort818 to decide...

**Comment by olantrust** [comment]
> @omni6 I try it... how about Q-logo?
> ![image](https://user-images.githubusercontent.com/8083855/50574637-a5280700-0e05-11e9-98eb-f8245927ea23.png)
> **Q**t**W**ebFlix

Looks amazing!

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/50574822-7c097580-0e09-11e9-84d2-29a0edf51fa5.png)

**Comment by omni6** [comment]
Love it!

**Comment by varlesh** [comment]
SVG source (rename zip to svg):
[qtwebflix.zip](https://github.com/gort818/qtwebflix/files/2719489/qtwebflix.zip)

**Comment by omni6** [comment]
This is the reason i love OSS collaboration. Thanks man!

**Comment by gort818** [comment]
@varlesh Awesome thank you so much!!
@omni6 I love all of them, hard to decide :(

**Comment by varlesh** [comment]
@gort818 All versions:
[icons.zip](https://github.com/gort818/qtwebflix/files/2719557/icons.zip)

**Comment by omni6** [comment]
@gort818 
imho the last one is most beautiful. Do you want to provide it instad of https://github.com/gort818/qtwebflix/blob/master/data/netflix-desktop.svg ?

**Comment by gort818** [comment]
@omni6 sure!

**Comment by olantrust** [comment]
> @varlesh Awesome thank you so much!!
> @omni6 I love all of them, hard to decide :(

They are all great.
Number 3 is perhaps the most vibrant one, but also the one which most signifies the purpose to the user, which definitely enhances usability, and possibly even usage (many users forget what software they have, or what icon is for what).

**Comment by gort818** [comment]
Ok cool I'll add it to the repo shortly

**Comment by gort818** [comment]
Ok added it to the repo.
@omni6 you can change the aur package now

@varlesh how would you like me to add your name to the authors list?

**Comment by gort818** [comment]
@omni6 thanks for the update! also how would you like to be added to the authors list?

**Comment by varlesh** [comment]
@gort818 hi, not needed. Use what you want

**Comment by varlesh** [comment]
@gort818 logo for readme:
![logo](https://user-images.githubusercontent.com/8083855/50625087-08698480-0f3f-11e9-88a3-5c65a4ed9e4b.png)

**Comment by gort818** [comment]
Fixed with 4e5f2b0

Thanks for all your help everyone
