### ISSUE TITLE
netflix password login not being saved

### ISSUE THREAD

**Issue by ryanmusante** [gort818/qtwebflix#48]
After recently rebuilding package, my login and username are no longer being saved in between sessions. 

~/.config/Qtwebflix contains Providers.conf and Save State.conf 

Should there be something else? Is there a setting within the application to check?

**Comment by gort818** [comment]
I cannot reproduce this issue, try removing your cache, ~/.cache/qtwebflix/

**Comment by ryanmusante** [comment]
Problem solved.
