### ISSUE TITLE
Menu with option to switch providers

### ISSUE THREAD

**Issue by olantrust** [gort818/qtwebflix#52]
For wider usage and better usability it would at some point be helpful to:

Allow the user to click on a 'menu' icon or button in the app to change providers, so as to expose the functionality. The location of the menu would of course depend on the user's system, but all systems would show it somewhere.

Alternatively a floating button that appears when the screen is touched / the mouse or trackpad is moved.

**Comment by gort818** [comment]
@olantrust you can right click to bring up the menu.
