### ISSUE TITLE
960x540 Playback with Shows that aren't made by netflix

### ISSUE THREAD

**Issue by xpander69** [gort818/qtwebflix#54]
the 1080p unblock plugin doesn't seem to work on non-netflix tv shows. Works fine with every netflix original one i tested so far.

qtwebflix 0.1.r161.g9168c4c
Arch Linux x86_64

Does anybody else have this issue?

![ss_07022019_22 33 35](https://user-images.githubusercontent.com/1345116/52441353-0b045e80-2b29-11e9-9bd8-102beee1f58c.png)

**Comment by gort818** [comment]
Yeah unfortunately this is normal, I cannot get all of the features of this https://github.com/truedread/netflix-1080p to work with qtwebflix.

**Comment by gort818** [comment]
@xpander69 and thanks for all your Linux gaming videos!
