### ISSUE TITLE
How to force use pepper-flash/hal-flash to enable HD on amazon prime?

### ISSUE THREAD

**Issue by bugandy** [gort818/qtwebflix#56]
Hello.

I'm trying to get HD when I watch movie on Amazon, I can't get it in html5 because there's not HDCP support on Linux for now (not DRM problem, TV-Series are OK, and problem is not just with qtwebflix, but with every browser).

I read about hal-flash library should be get HD support from Amazon, but it requires flash plug-in to work.

So, how I can force qtwebflix to use pepper-flash in order to work with hal-flash?

I try to do --register-pepper-plugins="/usr/lib/PepperFlash/libpepflashplayer.so" but qtwebflix follow to use widevine and get hdcp error.

I see pepper-flash in qtwebflix opt-depends, I think that means qtwebflix supports pepper-flash.

**Comment by gort818** [comment]
@bugandy Hey there, I have never heard of hal-flash I will look into it, if you have a link to some information regarding amazon with hal-flash please send it to me.

**Comment by bugandy** [comment]
That comment says it works: https://askubuntu.com/a/949876

But i do not understand if can works with pepper and/or qtwebflix.

Now I will to get some tests with waterfox/flashplugin in order to see HAL can really solve problem in that way.

**Comment by bugandy** [comment]
AAARGH!!! hal-flash seems not support on newer flash version and pepper flash:
https://wiki.archlinux.org/index.php/Flash_DRM_content

I run into a very old solution.. o_0

Sorry for lost time. This point seems not more chances to get Prime Video movie HD on linux.

**Comment by gort818** [comment]
@bugandy It looks like it is for flash drm and amazon uses html5 .. so I do not see how this is going to help. At least the tv shows are working I watched The Expanse in HD great show!

**Comment by bugandy** [comment]
Have you see my edit to my last post?

Also seems Amazon have dropped flash support some years ago, but continue supports silverlight on windows and mac... Next day I will investigate for pipelight chance.

How about pipelight support on qtwebflix?

And I know the TV shows works. I write it in my first post.
(Just for me is needed change user agent with a windows user agent because seems Amazon do not supports HD for linux at all, but at least do not require hdcp for TV shows).

**Comment by bugandy** [comment]
Hello. Sorry for off-topic. This is just for a comparison... do you have HD 1080p working on TV shows in Amazon?

Since yesterday I can't view anything in HD in amazon, nor in QTWebFlix neither in Waterfox.
I try to change user agent but nothing happened, I suspect Amazon identify me as Linux user through another way, do you have same issue?

Soon as possible I try with a pc-windows, but I think it just my problem.
