### ISSUE TITLE
Playback speed

### ISSUE THREAD

**Issue by jsteel44** [gort818/qtwebflix#6]
Is there any possibility of being able to alter the playback speed? For eg 1.1x and 1.2x would be great. Thanks!

**Comment by gort818** [comment]
@jsteel44 I looked into this, there is a chrome extension that allows this for html5 video players, so it might be possible I would do some more research and let you know of my findings!

**Comment by gort818** [comment]
I found this https://github.com/igrigorik/videospeed

I don't know a way to implement it yet.

**Comment by magiruuvelvet** [comment]
Scripts can be loaded with the QtWebEngine Script Collection class. It's a bit tricky though. I'm currently running my own experiments to get FrankerFaceZ loaded on Twitch via Qt. It mostly seems to fail on JavaScript promises.

**Comment by gort818** [comment]
@jsteel44 Sorry it has been so long but it looks like I got it working!

Now just to implement!

**Comment by jsteel44** [comment]
OK no problem thank you!

**Comment by gort818** [comment]
ok it is merged into master, give it a try!

**Comment by gort818** [comment]
@jsteel44 
![screenshot_20181209_122542](https://user-images.githubusercontent.com/9098121/49702550-3c56c180-fbae-11e8-8606-171ea463fa50.png)
Now with visualizer for netflix.

**Comment by xf-** [comment]
works for me

**Comment by gort818** [comment]
Awesome thanks!

**Comment by gort818** [comment]
added with ec1f17a5d5726be27a58787b5a39f5445970206d
