### ISSUE TITLE
qtwebflix starts with a black window

### ISSUE THREAD

**Issue by Nuc1eoN** [gort818/qtwebflix#69]
When starting the application I simply get a black window after the latest update.
Here's the error message:
`Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.`

This happens on Archlinux

**Comment by gort818** [comment]
@Nuc1eoN I think there is an issue with the latest QtWebEngine, try deleting your cache and data
 

1.  rm -r ~/.cache/qtwebflix  
2.  rm -r  ~/.local/share/qtwebflix/QtWebEngine/Default

**Comment by Nuc1eoN** [comment]
nvm with updated to the latest git and suddenly it works:)
