### ISSUE TITLE
1080p playback

### ISSUE THREAD

**Issue by BrianAllred** [gort818/qtwebflix#7]
The following repo is a Chrome extension enabling 1080p playback. Would it be possible to implement this?

https://github.com/truedread/netflix-1080p

**Comment by gort818** [comment]
I saw a reddit post about that yesterday, as far as I know chrome extensions are not supported in qtwebengine. If someone knows a way to get this to work that would awesome.

I will leave this open, I definitely  want to include this but not sure how yet.

**Comment by ryanmusante** [comment]
Is this using qtwebengine with the hotfix?

https://github.com/magiruuvelvet/LightweightQtDRMStreamViewer

URL Interceptor: Netflix 1080p hotfix2
UrlRequestInterceptor.cpp

**Comment by omni6** [comment]
hot! 
@gort818 can you implement this?

**Comment by gort818** [comment]
Hmm that is interesting I did not know another project like this existed, I can try to implement this today if I have time. :)

**Comment by omni6** [comment]
hmm, i dont get it to work...

**Comment by gort818** [comment]
@omni6 What do you mean?

**Comment by omni6** [comment]
I compiled https://github.com/magiruuvelvet/LightweightQtDRMStreamViewer just for interest. but when i run it i get:

> Netflix Player detected! Injecting Netflix 1080p Unlocker...
> js: Refused to execute script from 'https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-5.0008.803.011.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
> 

Before you make you a lot of work... try it yourself, perhaps i do something wrong. But for me it seems to be broken.

**Comment by ryanmusante** [comment]
Submit an issue on that side and we can work together to find a solution.

**Comment by gort818** [comment]
@omni6 I just tried it, same issue as you I also tried to implement it in qtwebflix but no luck :(

**Comment by ryanmusante** [comment]
I posted an issue requesting help on both hubs, maybe someone will be able to give some information.

**Comment by ryanmusante** [comment]
LightweightQtDRMStreamViewer has new commit which apparently fixes issue. He said if it fails again in future, he will post script.

**Comment by ryanmusante** [comment]
![screenshot from 2018-03-29 20-44-27](https://user-images.githubusercontent.com/26808646/38087174-1fd9a8c2-3392-11e8-8b6f-723a417aeb47.png)

**Comment by omni6** [comment]
first i thought i were on the wrong github page xD

**Comment by gort818** [comment]
Ok guys looks like we got it going.. I will close this for now until any issues arise.

close with a5eec25

**Comment by omni6** [comment]
Great!

**Comment by omni6** [comment]
```
mainwindow.cpp: In Konstruktor »MainWindow::MainWindow(QWidget*)«:
mainwindow.cpp:41:9: Fehler: »class MainWindow« hat kein Element namens »m_interceptor«
   this->m_interceptor = new UrlRequestInterceptor;
         ^~~~~~~~~~~~~
mainwindow.cpp:42:65: Fehler: »class MainWindow« hat kein Element namens »m_interceptor«
   this->webview->page()->profile()->setRequestInterceptor(this->m_interceptor);
                                                                 ^~~~~~~~~~~~~
make: *** [Makefile:1021: mainwindow.o] Fehler 1
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
:: Unable to build qtwebflix-git - makepkg exited with code: 2
```

**Comment by gort818** [comment]
@omni6 yeah sorry about that, it is fixed now :)

**Comment by omni6** [comment]
![screenshot](https://user-images.githubusercontent.com/24492439/38127646-5f84c60e-33f7-11e8-9900-dbb975bbf0b0.png)

**Comment by gort818** [comment]
@omni6 is that six from Battlestar Galactica?
Nice it is working :) good job everyone

**Comment by omni6** [comment]
hmm, you could be right! but it is so long ago i watched galactica... But really i struggle to watch all the nice already finished series again, but now in HD!! My wife would be totally horrified if i tell her that we must watch complete walking dead again. thanks @gort818

**Comment by ryanmusante** [comment]
How do you get the statistics screen?

**Comment by gort818** [comment]
Crtl alt shift d

**Comment by gort818** [comment]
@omni6 Then it is time for a rewatch! I know what you mean, I am trying to convince my wife to re-watch all of Stargate SG1 with me.

**Comment by soufianefariss** [comment]
You guys know a way to force 1080p on **HBO NOW**?

**Comment by gort818** [comment]
For me hbo streams at 1080p or at least it appears to be there are not any metrics to see but it looks fantastic. This is from there website. It adjust automatically I do not think there is a way to force it.. I could be wrong but I could not find anything atm.

> Is HBO NOW programming available in HD?
> Yes, most shows on HBO NOW are available in HD. When streaming video, HBO NOW automatically adjusts the video quality based on the download speed of your broadband connection.
