### ISSUE TITLE
Error Code: F7353-5101

### ISSUE THREAD

**Issue by jasonkhanlar** [gort818/qtwebflix#71]
When I try to play video content on Netflix, now I am getting this error code since sometime in the last 24 hours.
I found this: https://help.netflix.com/en/node/51013

If I run `qtwebflix --nonhd` then Netflix videos play at 720p without any errors.

**Comment by gort818** [comment]
Can confirm.. damnit netflix stop changing shit... I do not know if we continue to have any 1080p streams in qtwebflix :( Let me see if I can come up with anything.

**Comment by gort818** [comment]
Cannot get it to work so disabled it. Should work without the commandline option now.
