### ISSUE TITLE
unable to play videos due to ERROR: M7111-1331

### ISSUE THREAD

**Issue by Tasty213** [gort818/qtwebflix#73]
Hi,

I'm trying to this up to work with Netflix. I've successfully logged in but when I try to play any of the videos I get the error.
```
Streaming Error
This title is not available to watch instantly. Please try another title.
Error Code: M7111-1331
```
For reference I also got the same error with https://aur.archlinux.org/packages/netflix-qdesktop/  so is likely either a dependency or environment issue

**Comment by gort818** [comment]
When did you build qtwebflix?

**Comment by Tasty213** [comment]
Same day i submitted the issue

**Comment by jasonkhanlar** [comment]
I'm getting a similar issue now also. F7111-1331 error code for all videos
