### ISSUE TITLE
Error when installing on Mint

### ISSUE THREAD

**Issue by hrqmonteiro** [gort818/qtwebflix#75]
> Project MESSAGE: Qt 5.9.5 ScrollBars not supported in this version.
> Project ERROR: Unknown module(s) in QT: webenginewidgets
> Makefile:133: recipe for target 'sub-src-make_first-ordered' failed
> make: *** [sub-src-make_first-ordered] Error 3

This appears when i try to make, i installed every lib available and still got this.

**Comment by gort818** [comment]
Do you have qtwebengine5-dev installed?

**Comment by hrqmonteiro** [comment]
Yes i do, that's the reason i find it odd

**Comment by gort818** [comment]
That is odd, what version of mint are you using?

**Comment by hrqmonteiro** [comment]
19.2
Fresh install today on my gfs laptop. In my standard Arch setup i installled via AUR and all the qt dependencies are ok, but now on Mint is returning this error..

**Comment by gort818** [comment]
Yeah the packages on the Ubuntu based systems are separated differently than on Arch..
Hmm how about qtbase5-dev? If that does not work can you list all the qt libs you have installed I will try to narrow it down.

**Comment by hrqmonteiro** [comment]
Don't remember installing this one. At first i ran into a same mistake but with the qml module, so i installed qtwebengine5-dev and it solved, but then i ran into this one.

Not on pc right cause i'm at college, when i got home i'll install this one and report

**Comment by hrqmonteiro** [comment]
> Yeah the packages on the Ubuntu based systems are separated differently than on Arch..
> Hmm how about qtbase5-dev? If that does not work can you list all the qt libs you have installed I will try to narrow it down.

Yes, this one is installed and still returning this error.

**Comment by gort818** [comment]
How about libqt5webenginewidgets5? Can you give me a list of qt libs installed?

**Comment by hrqmonteiro** [comment]
I already have. Still the same error.
How can i give you such list?

**Comment by hrqmonteiro** [comment]
Now i can make it, i installed some libs i found on some stackoverflow answers, but i make, and then "qtwebflix command not found"

**Comment by hrqmonteiro** [comment]
Got it, it was some strange lib i couldn't find, now is working, thanks!

**Comment by gort818** [comment]
do you know what lib it was? Just in case another user has the same issue.
